# Generated by Django 5.2 on 2025-04-16 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="tourists",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
