# Generated by Django 5.2 on 2025-04-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_alter_location_tourists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="locationreview",
            constraint=models.UniqueConstraint(
                fields=("tourist", "location"), name="unique_location_review"
            ),
        ),
    ]
