# Generated by Django 5.2 on 2025-04-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_alter_locationreview_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourist",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_by", to="travel.location"
            ),
        ),
    ]
