# Generated by Django 5.2 on 2025-04-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_tourist_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_banners/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
