# Generated by Django 5.2 on 2025-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_homepagebanner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomepageBanner",
        ),
        migrations.DeleteModel(
            name="Tourist",
        ),
    ]
